config/routes.rb
Bh3site::Application.routes.draw do

  root "static#welcome"
  get "/hash/:id", to: "static#welcome"

  get "/about" => "about#index"
  get "about/history"
  get "about/mismanagement"

  get "calendar" => "static#calendar", as: :calendar

  get "static/welcome/:id", to: "static#welcome"
  get "static/events"

  get "more" => "more#index"
  get "more/email" => "more#index"
  get "more/away" => "more#away"
  get "more/trail" => "more#trail"
  get "more/habadashery" => "more#habadashery"
  get "more/policy" => "more#policy"

  get "posts/:page_number" => "posts#index", as: :hashtrash
  get "posts/index/:page_number" => "posts#index"
  get "posts" => "posts#index"

  get "events" => "special_events#index"
  get "events/:url_code" => "special_events#show"

resources :special_events, only: [] do
  resources :event_registrations, only: [:new, :create, :show]
end

  post "paypal" => "pay#catch"
  get "pay" => "pay#index"
  get "paypal/success/:url_code" => "pay#success"

  post "event_registrations/:id/delete" => "event_registrations#delete", as: :delete_registration

end

app/views/partials/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51699527-1', 'bostonhash.com');
  ga('send', 'pageview');

</script>

app/views/partials/_bh3_marathon_2015.html.erb
<h3><%= link_to "Rego now on Hashspace!", "https://store.hashspace.com/product.php?productid=17276&cat=0&page=1" %></h3>
<%= image_tag "marathon_2015_flyer.png", class: "marathon-image" %>
<h3><%= link_to "Rego now on Hashspace!", "https://store.hashspace.com/product.php?productid=17276&cat=0&page=1" %></h3>

app/views/partials/_bh3_marathon_2016.html.haml
%br
%p The Boston Hash House Harriers present...
= image_tag "marathon_2016_title.png"
%h3 The 2016 Boston Marathon Hash Weekend!
%p REGESTRATION COMING SOON!
%p April 16 - 18, 2016
%p= "Strap on your heels or strap your friend to a wall. Straighten your wig and don't forget the furry cuffs. What’s in your closet?"

%br

%h3 Rego pricing:
%p $69 through February 7th
%p $79 through March 31st
%p $89 thereafter

%br

%h3 Your $$$ gets you:
%p THREE DAYS OF EVENTS!
%p Saturday: Trail, Beer, Circle, Dinner, Give-Away, Dancing
%p Sunday: Fatboy trail, beer, circle
%p Monday: Watch the Marathon at Mile 20 with beer and food provided

%br

%p Get to Boston on Friday the 15th and kick the weekend off with a beer mile on the world famous esplanade and a pub crawl to follow!

%br

%p Crash space will be available for travel hashers! Just indicate that you'll need it when registering. 

%h3 Questions?
%p Email Orgasm Famine. orgasmfamine@gmail.com

app/views/partials/_marathon_2016.html.haml
- if flash[:notice]
  %h1
    = flash[:notice]
%br
%p The Boston Hash House Harriers present...
= image_tag "marathon_2016_title.png"
%h3 The 2016 Boston Marathon Hash Weekend!
%h2= link_to "REGO NOW!", new_special_event_event_registration_path(@event)
%p April 16 - 18, 2016
%p= "Strap on your heels or strap your friend to a wall. Straighten your wig and don't forget the furry cuffs. What’s in your closet?"

%br

%h3 Rego pricing:
%p $69 through February 9th
%p $79 through March 31st
%p $89 thereafter

%br

%h3 Your $$$ gets you:
%p THREE DAYS OF EVENTS!
%p Saturday: Trail, Beer, Circle, Dinner, Give-Away, Dancing
%p Sunday: Fatboy trail, beer, circle
%p Monday: Watch the Marathon at Mile 20 with beer and food provided

%br

%p Get to Boston on Friday the 15th and kick the weekend off with a beer mile on the world famous esplanade and a pub crawl to follow!

%br

%p
  Will you be in Boston earlier? There will be prelube events for the entire week before the event!
  %h1= link_to "Check out the schedule here!", "/2016_Boston_Marathon_hash_schedule_final.pdf"

%br

%p Crash space will be available for travel hashers! Just indicate that you'll need it when registering.

%br

%h3 Running the real Boston marathon?
%p You're eligible for a 26% discount on your rego price!
%p= ("Email #{mail_to 'orgasmfamine@gmail.com', "Orgasm Famine", subject: 'BH3 Marathon Rego Discount'} for details!").html_safe

%h3 Questions?
%p= mail_to "orgasmfamine@gmail.com", "Email Orgasm Famine", subject: "BH3 Marathon 2016"
%h2= link_to "REGO NOW!", new_special_event_event_registration_path(@event)

%br

%h3 Who's Cumming
.whos-coming-list{ style: "width: 40%;margin-left: auto;margin-right: auto;" }
  %table
    %tbody
      %tr
        %td{ style: "align: center;font-weight: bold;"} Hasher
        %td{ style: "align: center;font-weight: bold;"} Kennel
      - @event.event_registrations.order(:id).each do |rego|
        %tr
          %td #{rego.hash_name}
          %td #{rego.kennel}

app/views/partials/_marathon_2016_rego.html.haml
- if flash
  %h3= flash[:failure]
%h3 Marathon 2016 Rego Form
= simple_form_for [@event, @event_registration] do |f|
  = f.input  :hash_name
  = f.input  :nerd_name
  = f.input  :contact_email
  = f.input  :payment_email, label: "Payment Email (for PayPal)"
  = f.input  :kennel
  = f.label  :food_preference
  = f.select :food_preference, SpecialEvent::FOOD_OPTIONS
  %br
  = f.check_box :gluten_allergy, {}, 1, 0
  = f.label "I have a gluten allergy!"
  %br
  = f.check_box :need_crash_space, {}, 1, 0
  = f.label "I need crash space!"
  %br
  -# - if @event.extra_hab_type
  -#   %span.extra-hab-checkbox
  -#     = f.check_box  :extra_hab, {}, "#{@event.extra_hab_type}", nil
  -#   = f.label  "I want to purchase a #{@event.url_code.humanize} #{@event.extra_hab_type} for $#{@event.extra_hab_price.to_i}, which will be added to my rego price at checkout!"
  -#   %br
  -#   %span.extra-hab-size
  -#     = f.label  "#{@event.extra_hab_type} Size"
  -#     = f.select :extra_hab_size, SpecialEvent::HAB_SIZES
  %br
  %br
  %p You will be redirected to PayPal after registering to, you know, pay.
  %br
  = f.button :submit, "Register for BH3 Marathon Hash 2016"

:coffeescript
  $(document).ready ->
    $(".extra-hab-size").hide()
    $(".extra-hab-checkbox").click ->
      $(".extra-hab-size").toggle()
      return
    return

app/views/partials/_marathon_2017.html.haml
- if flash[:notice]
  %h1
    = flash[:notice]
%br
%p Back before there was hashing, back before there was even beer...there were
= image_tag "marathon_2017_logo.png", width: '500'
%h1 Cavemen and Dinosaurs!
%p Ae you a horny dinosaur? How large is your loincloth?

%h2= link_to "Rego Now!", new_special_event_event_registration_path(@event)

%br

%p Event: April 14th - 17th, 2017

%h3 Rego price: $89
%p "Check #{link_to "the BH3 calendar", "http://www.bostonhash.com/calendar"} for schedule updates."
%p **If you are ever lost or unsure where to go call or text the hotline at (617) 499-4835**

%br

%h3 Schedule
%p{ style: "color: red;" } Friday 4/14 Cumbridge Beer mile and pub crawl
%p When: 6:30HST (Beer mile) 8PM (Pub crawl)
%p Where: (new location)North Point Park, Boston. (Link to exact location to be posted on the calendar)
%p How much: $5 if you run the beer mile
%p -----------Pub crawl bars will be walking distance from North Station and on the calendar soon--------

%br

%p{ style: "color: red;" } Saturday 4/15 BH3 Pre-Historic Hash Marathon Main Event!
%p ***Check in and pick up your give-away when you arrive***
%p When: Noon if you want to brunch, 1PM if you want your free beer, Chalk talk starts at 1:30
%p Where: The Kinsale Irish Pub, 2 Center Plaza, Boston. Closest T stop Government Center
%p{ style: "color: green;"} YOU WILL NEED YOUR ID TO GET INTO THE ON-IN. If you are not a US citizen you will need your passport as your ID.

%br

%p{ style: "color: red;" } Sunday 4/16 Pink Taco Fatboy Trail
%p When: Noon HST (Get brunch if you want it and hares away at 1:30)
%p Where: Tavern in the Square Porter, 1815 Massachusetts Ave, Cambridge
%p What: There will be a 3-4 mile running trail and a shorter walkers trail. Beer checks will be together.

%br

%p{ style: "color: red;" }Monday 4/17 Watch the Actual Boston Marathon at mile 20
%p When: Elite runners go by around 11AM, normal runners around noon What: Hand out beer to the runners and hang out!
%p Food and beer provided by the hash
%p Where: Near mile 20 in Newton. Trail is marked from #{link_to "the Newton Centre T stop", "https://goo.gl/maps/9UrSBZVL7iQ2"}.

%br

%p{ style: "color: red;" }Monday 4/17 Ballbuster Trail!
%p What: Run a 6.9+ mile long trail that ends at mile 20!
%p When: 10:00 HST, hare(s) away 10:15, pack 10:30
%p Where: JFK park. Prelube will be marked from Harvard T
%p How much: $1 and a six pack
%p **Expect to get to mile 20 during the later waves of runners going by**

%br

%h3 Running the real r*cist Boston marathon?
%p You're eligible for a 26% discount on your rego price!
%p= ("Email #{mail_to 'orgasmfamine@gmail.com', "Orgasm Famine", subject: 'BH3 Marathon Rego Discount'} for details!").html_safe

%br

%h3 Questions?
%p= mail_to "orgasmfamine@gmail.com", "Email Orgasm Famine", subject: "BH3 Marathon 2016"

%br

%h2= link_to "Rego Now!", new_special_event_event_registration_path(@event)

%br

%h3 Who's Cumming
.whos-coming-list{ style: "width: 40%;margin-left: auto;margin-right: auto;" }
  %table
    %tbody
      %tr
        %td{ style: "align: center;font-weight: bold;"} Hasher
        %td{ style: "align: center;font-weight: bold;"} Kennel
      - @event.event_registrations.order(:id).each do |rego|
        %tr
          %td #{rego.hash_name}
          %td #{rego.kennel}

app/views/partials/_marathon_2017_rego.html.haml
- if flash
  %h3= flash[:failure]
%h3 Marathon 2017 Rego Form
= simple_form_for [@event, @event_registration] do |f|
  = f.input  :hash_name
  = f.input  :nerd_name
  = f.input  :contact_email
  = f.input  :payment_email, label: "Payment Email (for PayPal)"
  = f.input  :kennel
  = f.label  :food_preference
  = f.select :food_preference, SpecialEvent::FOOD_OPTIONS
  %br
  = f.check_box :gluten_allergy, {}, 1, 0
  = f.label "I have a gluten allergy!"
  %br
  = f.check_box :need_crash_space, {}, 1, 0
  = f.label "I need crash space!"
  %br
  %p You will be redirected to PayPal after registering to, you know, pay.
  %br
  = f.button :submit, "Register for BH3 Marathon Hash 2016"

app/views/partials/_marathon_2018.html.haml
- if flash[:notice]
  %h1
    = flash[:notice]
%br

%p The Boston Hash House Harriers present 

%h1 Hashy Potter and the Wicked Magical Marathon

= image_tag "marathon_2018_logo.png"

%p April 14 - 16, 2018

%p I solemnly swear we are up to no good. Get those wands at the ready and start practicing your swish and flicks. The hash is taking the rage train to Hogwarts! Get sorted into your house, earn house points and maybe win the Rage cup. It’s time for a butter beer down down.

%h2= link_to "Rego Now!", new_special_event_event_registration_path(@event)

%br

%h3 Rego pricing:
%p $69 through February 9th
%p $79 through March 31st
%p $89 thereafter

%h3 Your $$$ gets you THREE DAYS OF EVENTS!

%p Saturday, April 14: Trail, Beer, Circle, Dinner, Give-Away, Dancing

%p Sunday, April 15: Fatboy trail, beer, circle

%p Monday, April 16: Watch the Marathon at Mile 20 with beer and food provided

%br

%p We will do our best to find crash space travel hashers, but space is limited. Please indicate that you'll need it when registering or if you are able to host travel hashers.

%br

%p Running the real Boston marathon?
%p 10 points for Gryffindor! You're eligible for a 26% discount on your rego price!

%br

%h4 Marathon Week Schedule

%p Will you be in Boston earlier? There will be prelube events for the entire week before the event! Check out our <a href='/calendar'>calendar</a> for the most up-to-date infromation.

%p Monday, April 9th: Rhode Island H3 - Hash starts at 42.021560, -71.327434 (Nelson Field, Everett Skinner Rd, Plainville, MA) - 6:00pm (pack away 6:30pm sharp)

%p Tuesday, April 10th: Eager 4 Beaver - Hash starts at Shake Shack (in 'The Street' strip mall) 49 Boylston Street, Chestnut Hill - 6:30pm

%p Wednesday, April 11th: Boston Ballbuster Hardcore H3 - Hash starts at The Field (20 Prospect St, Cambridge) - 6:30pm

%p Thursday, April 12th: Pink Taco Trotters H3 - Hash starts at Tavern At the End of the World (108 Cambridge St, Charlestown) - 6:30pm (Everyone welcome, not just the ladies!)

%p Friday, April 13th: Boston Moon Beer Mile and Bar Crawl - Bar crawl starts at Boston Beer Works, 112 Canal St - 5:00pm

%p Beer Mile is at North Point Park 6 Museum Way, Cambridge - 7:00pm sharp - Please do not arrive before 6:30pm

%br

%p= mail_to "egrafeld@gmail.com", "Email Udder Whore for Questions/Details", subject: "BH3 Marathon 2018"
%p Check #{link_to "the BH3 calendar", "http://www.bostonhash.com/calendar"} for schedule updates and info on trails leading up to the main event!
%p **If you are ever lost or unsure where to go, text the hotline at (617) 499-4835**

%br

%h2= link_to "Rego Now!", new_special_event_event_registration_path(@event)

%br

%p By registering you are agreeing to take responsibility for your own actions during the entire weekend of events. That includes treating our city, members of the hash, and greater community with respect.  Any inappropriate behavior can result in forfeiting your rego, being banned from the Boston Hash, or being reported to the authorities. 

%p As always, this is a 21+ event

%br

%h3 Who's Cumming
.whos-coming-list{ style: "width: 40%;margin-left: auto;margin-right: auto;" }
  %table
    %tbody
      %tr
        %td{ style: "align: center;font-weight: bold;"} Hasher
        %td{ style: "align: center;font-weight: bold;"} Kennel
      - @event.event_registrations.where(status: ACTIVE).order(:id).each do |rego|
        %tr
          %td #{rego.hash_name}
          %td #{rego.kennel}

app/views/partials/_marathon_2018_rego.html.haml
- if flash
  %h3= flash[:failure]
%h3 Marathon 2018 Rego Form
= simple_form_for [@event, @event_registration] do |f|
  = f.input  :hash_name
  = f.input  :nerd_name
  = f.input  :contact_email
  = f.input  :payment_email, label: "Payment Email (for PayPal)"
  = f.input  :kennel
  = f.label  :food_preference
  = f.select :food_preference, SpecialEvent::FOOD_OPTIONS
  %br
  = f.check_box :gluten_allergy, {}, 1, 0
  = f.label "I have a gluten allergy!"
  %br
  = f.check_box :dairy_free, {}, 1, 0
  = f.label "I am dairy free!"
  %br
  = f.check_box :need_crash_space, {}, 1, 0
  = f.label "I need crash space!"
  %br
  = f.check_box :have_crash_space, {}, 1, 0
  = f.label "I have crash space!"
  %br
  -# - if @event.extra_hab_type
  -#   %span.extra-hab-checkbox
  -#     = f.check_box  :extra_hab, {}, "#{@event.extra_hab_type}", nil
  -#   = f.label  "I want to purchase a #{@event.url_code.humanize} #{@event.extra_hab_type} for $#{@event.extra_hab_price.to_i}, which includes free tax prepration services and will be added to my rego price at checkout!"
  -#   %br
  -#   %span.extra-hab-size
  -#     = f.label  "#{@event.extra_hab_type} Size"
  -#     = f.select :extra_hab_size, SpecialEvent::HAB_SIZES

  %p You will be redirected to PayPal after registering to, you know, pay.
  %br
  = f.button :submit, "Register for BH3 Marathon Hash 2018"

app/views/partials/_marathon_2019.html.haml
- if flash[:notice]
  %h1
    = flash[:notice]
%br

%p The Boston Hash House Harriers present 

%h1 Game of Boners: A Song of Fireball and Smirnoff Ice

%p April 13 - 15, 2019

%p In the Game of Boners, you either rage or you dragon. Hashers seek the mythical tale of good beer and shots, while the ancient enemies Smirnoff Ice and Fireball return after being dormant for thousands of seconds. A hasher always finishes their drink, so join us in waving a giant middle finger to the god of sobriety! For the night is long and full of UGHs...

%h2= link_to "Rego Now!", new_special_event_event_registration_path(@event)

%br

%h3 Your $$$ gets you THREE DAYS OF EVENTS!

%p Saturday, April 13: Trail, Beer, Circle, Dinner, Give-Away, Dancing

%p Sunday, April 14: Fatboy trail, beer, circle, Games of Thrones screening 

%p Monday, April 15: Watch the Marathon at Mile 20 with beer and food provided

%br

%h3 Rego pricing:

%p $69 through February 8th
%p $79 through March 31st
%p $89 thereafter

%br

%h3 C*mming Early?

%p Get to Boston on Friday the 12th and kick the weekend off with a beer mile and pay as you go pub crawl. Even earlier? There will be prelube events for the entire week before the event!

%p Check #{link_to "the BH3 calendar", "http://www.bostonhash.com/calendar"} for schedule updates and info on trails leading up to the main event!

%br

%h3 Need Crash Space?

%p We will do our best to find crash space travel hashers, but space is limited. Please indicate that you'll need it when registering or if you are able to host travel hashers.

%br

%h3 Running the other, less fun Boston marathon?

%p You know nothing, hasher.  You're eligible for a 26.2% discount on your rego price!

%p= mail_to "oboneronon@gmail.com", "Email O'Bone'R for questions/details!", subject: "BH3 Marathon 2019"

%br

%h2= link_to "Rego Now!", new_special_event_event_registration_path(@event)

%p By registering you are agreeing to take responsibility for your own actions during the entire weekend of events. That includes treating our city, members of the hash, and greater community with respect.  Any inappropriate behavior can result in forfeiting your rego, being banned from the Boston Hash, or being reported to the authorities. 

%p As always, this is a 21+event

%br

%h3 Who's Cumming
.whos-coming-list{ style: "width: 40%;margin-left: auto;margin-right: auto;" }
  %table
    %tbody
      %tr
        %td{ style: "align: center;font-weight: bold;"} Hasher
        %td{ style: "align: center;font-weight: bold;"} Kennel
      - @event.event_registrations.where(status: ACTIVE).order(:id).each do |rego|
        %tr
          %td #{rego.hash_name}
          %td #{rego.kennel}

app/views/partials/_marathon_2019_rego.html.haml
- if flash
  %h3= flash[:failure]
%h3 Marathon 2019 Rego Form
= simple_form_for [@event, @event_registration] do |f|
  = f.input  :hash_name
  = f.input  :nerd_name
  = f.input  :contact_email
  = f.input  :payment_email, label: "Payment Email (for PayPal)"
  = f.input  :kennel
  = f.label  :food_preference
  = f.select :food_preference, SpecialEvent::FOOD_OPTIONS
  %br
  = f.check_box :gluten_allergy, {}, 1, 0
  = f.label "I have a gluten allergy!"
  %br
  = f.check_box :dairy_free, {}, 1, 0
  = f.label "I am dairy free!"
  %br
  = f.check_box :need_crash_space, {}, 1, 0
  = f.label "I need crash space!"
  %br
  = f.check_box :have_crash_space, {}, 1, 0
  = f.label "I have crash space!"
  %br
  -# - if @event.extra_hab_type
  -#   %span.extra-hab-checkbox
  -#     = f.check_box  :extra_hab, {}, "#{@event.extra_hab_type}", nil
  -#   = f.label  "I want to purchase a #{@event.url_code.humanize} #{@event.extra_hab_type} for $#{@event.extra_hab_price.to_i}, which will be added to my rego price at checkout!"
  -#   %br
  -#   %span.extra-hab-size
  -#     = f.label  "#{@event.extra_hab_type} Size"
  -#     = f.select :extra_hab_size, SpecialEvent::HAB_SIZES

  %p You will be redirected to PayPal after registering to, you know, pay.
  %br
  = f.button :submit, "Register for BH3 Marathon Hash 2019"

app/views/partials/_marathon_2020.html.haml
- if flash[:notice]
  %h1
    = flash[:notice]
%br

%p The Boston Hash House Harriers present 

%h1 Boston H3's - The Flying 'Marathon' Circus

%p April 17 - 20, 2020

<<<<<<< HEAD
%p Strange women lying in ponds distributing beer, is no basis for a major event! Do we care? NO! After all there's nothing wrong with you that an extensive trail can't prolong. Join us for our Marathon main event, where we'll we seek the holy grails (of beer), quest for shrubberies (and shots), and chase hares shouting "ni" across our fair city.
=======
%p Strange women lying in ponds distributing beer, is no basis for a major event! Do we care? NO! After all there's nothing wrong with you that an extensive trail can't prolong. Join us for our Marathon main event, where we'll we seek the holy grails (of beer), quest for shrubberies (and shots), and be known as the r*unners who say "ON-ON" all throughout Boston.
>>>>>>> 6ee2273b7e2e43f8bdb7a33b4bdbbc5a234edb99

%p And now for something completely different.

%h2= link_to "Rego Now!", new_special_event_event_registration_path(@event)

%br

%h3 Your $$$ gets you FOUR DAYS OF EVENTS!

%p Friday, April 17: BEER/SILLY WALK MILE (and pay as you go bar-crawl)

%p Saturday, April 18: Trail, Beer, Circle, Dinner, Give-Away, Dancing

%p Sunday, April 19: Fatboy trail, beer, circle

%p Monday, April 20: Watch the Marathon at Mile 20 with beer and food provided

%br

%h3 Rego pricing:

%p $69 through February 8th
%p $99 through March 31st
%p $109 thereafter
%p $120 DAY OF 

%br

%h3 C*mming Early?

%p We’ve got huge tracts of… trails. Join us starting Sunday, April 10 when we kick-off this week of shenanigans.  

%p Check #{link_to "the BH3 calendar", "http://www.bostonhash.com/calendar"} for schedule updates and info on trails leading up to the main event!

%br

%h3 Coming by way of African or European Swallow? 

%p We will do our best to find crash space travel hashers, but space is limited. Please indicate that you'll need it when registering or if you are able to host travel hashers.

%br

%h3 Running the other, less fun Boston marathon?

%p Could be worse, you could be running a cajun! You're eligible for a 26.2% discount on your rego price.

%p= mail_to "BlondieMcFcksalot@gmail.com", "Email Blondie for detrails!", subject: "BH3 Marathon 2020 - R*cists"

%br

%h2= link_to "Rego Now!", new_special_event_event_registration_path(@event)

%p By registering you are agreeing to take responsibility for your own actions during the entire weekend of events. That includes treating our city, members of the hash, and greater community with respect.  Any inappropriate behavior can result in forfeiting your rego, being banned from the Boston Hash, or being reported to the authorities. 

%p As always, this is a 21+event

%br

%h3 Who's Cumming
.whos-coming-list{ style: "width: 40%;margin-left: auto;margin-right: auto;" }
  %table
    %tbody
      %tr
        %td{ style: "align: center;font-weight: bold;"} Hasher
        %td{ style: "align: center;font-weight: bold;"} Kennel
      - @event.event_registrations.where(status: ACTIVE).order(:id).each do |rego|
        %tr
          %td #{rego.hash_name}
          %td #{rego.kennel}

app/views/partials/_marathon_2020_rego.html.haml
- if flash
  %h3= flash[:failure]
%h3 Marathon 2020 - Boston H3's - The Flying 'Marathon' Circus - Rego Form
= simple_form_for [@event, @event_registration] do |f|
<<<<<<< HEAD
  = f.input  :hash_name, label: "What is your name?"
=======
  = f.input  :hash_name, label: "What is your hash name?"
>>>>>>> 6ee2273b7e2e43f8bdb7a33b4bdbbc5a234edb99
  = f.input  :kennel, label: "With which kennel is your quest?"
  = f.input  :nerd_name
  = f.input  :contact_email
  = f.input  :payment_email, label: "Payment Email (for PayPal)"
<<<<<<< HEAD
  = f.label  "Would you like Spam, Spam, Spam, Spam, Spam, Spam, baked beans, Spam, Spam, Spam and Spam, or Spam, Spam, Spam, Spam, Spam, Spam, baked beans, Spam, Spam, Spam and Spam, hold the Spam?"
  = f.select :food_preference, SpecialEvent::FOOD_OPTIONS
  %br
=======
  = f.label  "Dietary preference, i.e. would you like Spam, Spam, Spam, Spam, Spam, Spam, baked beans, Spam, Spam, Spam and Spam, or Spam, Spam, Spam, Spam, Spam, Spam, baked beans, Spam, Spam, Spam and Spam, hold the Spam?"
  = f.select :food_preference, SpecialEvent::FOOD_OPTIONS
  %br
  %br
>>>>>>> 6ee2273b7e2e43f8bdb7a33b4bdbbc5a234edb99
  = f.check_box :gluten_allergy, {}, 1, 0
  = f.label "I have a gluten allergy!"
  %br
  = f.check_box :dairy_free, {}, 1, 0
  = f.label "I am dairy free!"
  %br
<<<<<<< HEAD
=======
  %br
>>>>>>> 6ee2273b7e2e43f8bdb7a33b4bdbbc5a234edb99
  = f.check_box :need_crash_space, {}, 1, 0
  = f.label "I need crash space!"
  %br
  = f.check_box :have_crash_space, {}, 1, 0
  = f.label "I have crash space!"
  %br
  -# - if @event.extra_hab_type
  -#   %span.extra-hab-checkbox
  -#     = f.check_box  :extra_hab, {}, "#{@event.extra_hab_type}", nil
  -#   = f.label  "I want to purchase a #{@event.url_code.humanize} #{@event.extra_hab_type} for $#{@event.extra_hab_price.to_i}, which will be added to my rego price at checkout!"
  -#   %br
  -#   %span.extra-hab-size
<<<<<<< HEAD
  -#     = f.label  "#{@event.extra_hab_type} Size"
  -#     = f.select :extra_hab_size, SpecialEvent::HAB_SIZES
=======
  = f.label  "Shirt Size, for a giveaway, maybe?"
  = f.select :extra_hab_size, SpecialEvent::HAB_SIZES
>>>>>>> 6ee2273b7e2e43f8bdb7a33b4bdbbc5a234edb99

  %p You will be redirected to PayPal after registering to, you know, pay.
  %br
  = f.button :submit, "Register for BH3 Marathon Hash 2020"