config/routes.rb
Bh3site::Application.routes.draw do

  root "static#welcome"
  get "/hash/:id", to: "static#welcome"

  get "/about" => "about#index"
  get "about/history"
  get "about/mismanagement"

  get "calendar" => "static#calendar", as: :calendar

  get "static/welcome/:id", to: "static#welcome"
  get "static/events"

  get "more" => "more#index"
  get "more/email" => "more#index"
  get "more/away" => "more#away"
  get "more/trail" => "more#trail"
  get "more/habadashery" => "more#habadashery"
  get "more/policy" => "more#policy"

  get "posts/:page_number" => "posts#index", as: :hashtrash
  get "posts/index/:page_number" => "posts#index"
  get "posts" => "posts#index"

  get "events" => "special_events#index"
  get "events/:url_code" => "special_events#show"

resources :special_events, only: [] do
  resources :event_registrations, only: [:new, :create, :show]
end

  post "paypal" => "pay#catch"
  get "pay" => "pay#index"
  get "paypal/success/:url_code" => "pay#success"

  post "event_registrations/:id/delete" => "event_registrations#delete", as: :delete_registration

end

app/controllers/posts_controller.rb
require 'rss'
class PostsController < ApplicationController
  def index
    params["page_number"] ||= "1"
    @page_number = params["page_number"].to_i
    @posts = get_posts_for_page(@page_number)
  end
  
  private
  def get_posts_for_page(page)
      start_index = ((page - 1) * 5) + 1 
      @rss_url = 'http://bostonhash.blogspot.com/feeds/posts/default?alt=rss&max-results=5&start-index=' + start_index.to_s
      begin
          latest_blog_posts = RSS::Parser.parse(open(@rss_url).read, false).items
        rescue => error
          # Do nothing, just continue.  The view will skip the hash trash section if the feed is nil.
          latest_blog_posts = nil
        end
      return latest_blog_posts
  end
end

app/views/posts/index.html.erb
<div>
   <h4>Hash Trash</h4>
<p>Missed a hash?  Catch up on all the trash here...</p>
<% if @posts != nil and @posts.length > 0 then %>
<p>
<%if @page_number != 1%><a href="<%=hashtrash_path(page_number:@page_number-1)%>"><i class="fa fa-arrow-left"></i></a> | <%end%>	
<% @posts.each_with_index do |post, i| %>
<a href="#" title="previous page of hash trashes" 
onclick="return scrollToElement('<%=post.title.gsub(/[^0-9a-z ]/i, "").gsub(/\s+/, "")%>');"><%=post.title%></a> |
<% end %>
<a title="next page of hash trashes" href="<%=hashtrash_path(page_number:@page_number+1)%>"><i class="fa fa-arrow-right"></i></a>
</p>
<table>
	<% @posts.each_with_index do |post, i| %>
		<tr id="<%=post.title.gsub(/[^0-9a-z ]/i, '').gsub(/\s+/, "")%>">
			<td><%= link_to post.title, post.link, :target => "_blank" %>
(<%= time_ago_in_words(post.pubDate) %> ago) <% if i!=0%><a href="#" title="back to top" onclick="return scrollToTop();"><i class="fa fa-arrow-up"></i></a><%end%>
<br />
<%=raw(post.description)%>
<hr />
			</td>
		</tr>	
		<% end %>
</table>
<% else %>
<p>
<em>No hash trash to show.</em>
</p>
<% end %>
</div>