config/routes.rb
Bh3site::Application.routes.draw do

  root "static#welcome"
  get "/hash/:id", to: "static#welcome"

  get "/about" => "about#index"
  get "about/history"
  get "about/mismanagement"

  get "calendar" => "static#calendar", as: :calendar

  get "static/welcome/:id", to: "static#welcome"
  get "static/events"

  get "more" => "more#index"
  get "more/email" => "more#index"
  get "more/away" => "more#away"
  get "more/trail" => "more#trail"
  get "more/habadashery" => "more#habadashery"
  get "more/policy" => "more#policy"

  get "posts/:page_number" => "posts#index", as: :hashtrash
  get "posts/index/:page_number" => "posts#index"
  get "posts" => "posts#index"

  get "events" => "special_events#index"
  get "events/:url_code" => "special_events#show"

resources :special_events, only: [] do
  resources :event_registrations, only: [:new, :create, :show]
end

  post "paypal" => "pay#catch"
  get "pay" => "pay#index"
  get "paypal/success/:url_code" => "pay#success"

  post "event_registrations/:id/delete" => "event_registrations#delete", as: :delete_registration

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

  def history
  end
  
  def mismanagement
  end
end

app/views/about/history.html.erb
<div>
    <h4>Hash History</h4>

	<div id="page-content">


	<blockquote>
	<p><strong>ANCIENT HARRIERS</strong><br>
	Hash House Harrier roots extend back to the old English schoolboy game of "Hares and Hounds," in which some players, called "hounds," chase others, called "hares," who have left a trail of paper scraps along their route across fields, hedges, streams, bogs, and hills. One of the earliest Hares and Hounds events on record was the "Crick Run" at Rugby School in Warwickshire, England, first held in 1837. Hare and Hounds as an adult sport began in the fall of 1867 with a group of London oarsmen who wanted to keep fit during the winter. Also called "Paper Chasing" or the "Paper Chase," the game became very popular after its introduction on Wimbledon Common in 1868 by the Thames Hare and Hounds. Early clubs called themselves "Hare and Hounds" or simply "Harriers."</p>
	</blockquote>
	<blockquote>
	<p><strong>THE HASH IS BORN</strong><br>
	The Hash House Harriers as we know it today was founded in Malaya (now Malaysia) by Albert Stephen Ignatius Gispert, an English chartered accountant. It was sometime during 1937 when Gispert (or simply "G" as he was known to his friends) acquired a taste for the paper chase with the Springgit Harriers in Malacca (also in Malaya). Shortly after being transferred by his accounting firm to Kuala Lumpur he gathered together a number of fellow expatriate businessmen to form a harrier group. The first run was held in in December 1938 and the founding members included Cecil H. Lee, Frederick "Horse" Thomson, Eric Galvin, H.M. Doig, and Ronald "Torch" Bennet.</p>
	</blockquote>
	<blockquote>
	<p><strong>THE NAME "HASH"</strong><br>
	The group's name came about primarily because local authorities required legal registration of the club. While the "Kuala Lumpur Harriers" would have appeared a logical choice, "G" decided instead to use the nickname for the Selangor Club where a number of the local harriers both lived and took their meals. It seems that due to its lackluster food, the dining room was commonly referred to as the "Hash House."</p>
	</blockquote>
	<blockquote>
	<p><strong>HASH PHILOSOPHY</strong><br>
	The philosophy of the original Hash House Harriers from their 1938 charter is:</p>
	<ol>
	<li>To promote physical fitness among our members</li>
	<li>To get rid of weekend hangovers</li>
	<li>To acquire a good thirst and to satisfy it in beer</li>
	<li>To persuade the older members that they are not as old as they feel</li>
	</ol>
	</blockquote>
	<blockquote>
	<p><strong>MODERN HARRIERS</strong><br>
	Hashing in Kuala Lumpur was suspended during the World War II occupation by Japanese forces, but then reestablished after peace returned. It wasn't long before the hash began slowly spreading around the world. Former members of the original Hash House Harriers started a hash in 1947 near Milan, Italy, but it wasn't until 1962 that the next group was formed in Singapore. The Singapore Hash was gradually followed by others until in 1973 there were approximately 35 hashes in 14 countries. Subsequently, the hash began spreading like wildfire and the number of hashes soon climbed into the hundreds by the early 1980s. Today (1999) there are some 1,700 active hashes in over 180 countries, including approximately 350 in the United States. View a list of all the hashes in the world <a href="/hashdirectory">here</a>.</p>
	</blockquote>
	<p>provided courtesy of <a href="http://harrier.net/index2.html">Harrier Net</a></p>

	                    </div>
</div>

app/views/about/index.html.erb
<div>
    <h4>About the BH3</h4>

    <h3>Welcome to the Boston Hash House Harriers</h3>
    <p>
We are the Boston Hash House Harriers!
    </p>
<p>
	We're part of the global Hash House Harriers.  If you're familiar with that, we're the Boston group.  If you're not - here's some info on what this is all about.  You also might want to learn a bit more about <%=link_to 'the history of hashing', controller: 'about', action: 'history'%>.
</p>
<h4>What is a hash?</h4>
<p>
	A 'hash' is in short a 'run'.  A 'hare' sets a trail using chalk or flour or some other stuff.  Everyone meets at a predetermined place, known as the 'prelube' and get some rudimentary instructions about the days trail.  
</p>
<p>A 'hash' involves a trail that is set by some unlucky group of hashers, typically a lead and some helpers. These poor sods are known as the 'hares'. This also leads to the use of the terms 'harriers' (male) and 'harriettes' (female) when referencing hashers in general. The trails themselves are anywhere between three and six miles long. Trail is typically marked in flour or chalk.</p>
<h4>When do you hash in Boston?</h4>
<p>We typically hash on Wednesday evenings in the warmer months and Sunday afternoons in the cooler ones.  But there are loads of exceptions, special events,etc so check <%=link_to 'our calendar', calendar_path %> or <%=link_to 'front page', root_path%> for next hash details.  You might also want to <%=link_to 'join our email list', more_path%> to get more frequent updates.</p>
<h4>How do I join?</h4>
<p>Just show up.  That's it really.  There are no annual dues.  There is no sign up.  We're a welcoming bunch.  Hash cash is somewhere between $5-$15 depending on what the trail entails and is usually collected at the start.</p>
</div>

app/views/about/mismanagement.html.erb
<div>
    <h4>Mismanagement</h4>
<p>The following unlucky wankers were democratically erected (like a deer in headlights) as Boston H3 Mismanagement. They are chosen mostly due to their lack of organizational skills, personal hygiene, and original excuses. Basically, these are the people that can you can blame for everything that goes wrong.</p>
<%= render 'partials/misman/current' %>
<ul>
<li>
<%= render 'partials/misman/m1920' %>
  </li>
  <li>
<%= render 'partials/misman/m1819' %>
  </li>
  <li>
<%= render 'partials/misman/m1718' %>
  </li>
  <li>
<%= render 'partials/misman/m1617' %>
  </li>
  <li>
<%= render 'partials/misman/m1516' %>
  </li>
  <li>
<%= render 'partials/misman/m1415' %>
  </li>
  <li>
<%= render 'partials/misman/m1314' %>
  </li>
	<li>
<%= render 'partials/misman/m1213' %>
	</li>
	<li>
<%= render 'partials/misman/m1112' %>
	</li>
	<li>
<%= render 'partials/misman/m1011' %>
	</li>
	<li>
<%= render 'partials/misman/m0910' %>
	</li>
	<li>
<%= render 'partials/misman/m0809' %>
	</li>
	<li>
<%= render 'partials/misman/m0708' %>
	</li>
	<li>
<%= render 'partials/misman/gms' %>
	</li>
</ul>
</div>