config/routes.rb
Bh3site::Application.routes.draw do

  root "static#welcome"
  get "/hash/:id", to: "static#welcome"

  get "/about" => "about#index"
  get "about/history"
  get "about/mismanagement"

  get "calendar" => "static#calendar", as: :calendar

  get "static/welcome/:id", to: "static#welcome"
  get "static/events"

  get "more" => "more#index"
  get "more/email" => "more#index"
  get "more/away" => "more#away"
  get "more/trail" => "more#trail"
  get "more/habadashery" => "more#habadashery"
  get "more/policy" => "more#policy"

  get "posts/:page_number" => "posts#index", as: :hashtrash
  get "posts/index/:page_number" => "posts#index"
  get "posts" => "posts#index"

  get "events" => "special_events#index"
  get "events/:url_code" => "special_events#show"

resources :special_events, only: [] do
  resources :event_registrations, only: [:new, :create, :show]
end

  post "paypal" => "pay#catch"
  get "pay" => "pay#index"
  get "paypal/success/:url_code" => "pay#success"

  post "event_registrations/:id/delete" => "event_registrations#delete", as: :delete_registration

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boston Hash House Harriers ~ A Drinking Club With A Running Problem</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet">
<!-- bootstrap cdn-->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= yield :head %>
</head>
<body>

    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Home", root_url, class: "navbar-brand" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
					<li class="dropdown">
					          <a href="#" class="dropdown-toggle" data-toggle="dropdown">About the BH3 <b class="caret"></b></a>
					          <ul class="dropdown-menu">
					            <li><%= link_to "What the?", about_url %></li>
								<li><a href="/about/mismanagement">Boston H3 Mismanagement</a></li>
					            <li><a href="/about/history">History of the Hash House Harriers</a></li>
					          </ul>
				   </li>
		            <li><a href="/calendar">Calendar</a></li>
		            <li><a href="/events">Events</a></li>
					<li><a href="/posts">Hash Trash</a></li>
					<li class="dropdown">
					          <a href="#" class="dropdown-toggle" data-toggle="dropdown">More info <b class="caret"></b></a>
					          <ul class="dropdown-menu">
						                <li><a href="/more/email">Join our email groups</a></li>
								<li><a href="/more/away">Other Area Kennels</a></li>
								<li><a href="/more/policy">Policy on Sexual Misconduct</a></li>
								<li><a href="/more/trail">Laying trail</a></li>
								<li><a href="/more/habadashery">Habadashery</a></li>
								<li><a href="http://bostonhash.wdfiles.com/local--files/hash-songs/hymnal.pdf" target="_new">Hash Songbook</a></li>
					          </ul>
				   </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="header-image">
        <div class="headline">
            <div class="container">
                <h1>Boston<br />Hash House Harriers</h1>
                <h2>a drinking club with a running problem</h2>
            </div>
        </div>
    </div>
    <!-- /header-image -->

    <div class="container">

<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '867725033656914');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=867725033656914&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->

	<%= yield %>

    <hr />

        <!-- FOOTER -->
        <footer>
<p>Follow the Boston Hash House Harriers on <a href="https://twitter.com/bostonhash" target="_new"><i class="fa fa-twitter"></i> twitter</a>.  Lost on trail?  Call our hotline for an update:  <a href="tel:617-499-4835"><i class="fa fa-phone"></i> (617) 499-4835</a></p>
<p>Copyright &copy; Boston Hash House Harriers 2020</p>
        </footer>
        <!-- /END OF FOOTER -->

    </div>
    <!-- /container -->

    <!-- JavaScript -->

<%= yield :footer %>
<%= render 'partials/analytics' %>
</body>

</html>